/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inspectit.ocelot.configuration.docs;

import java.io.*;

public class Documentation {

    public static void main(String[] args) throws IOException {
        DocGenerator docGenerator = new DocGenerator();
        docGenerator.parseConfig(
                "C:\\Users\\awi\\Documents\\GitHub\\inspectit-ocelot-configuration-docs\\" +
                        "inspectit-ocelot\\inspectit-ocelot-config\\src\\main\\resources\\rocks\\inspectit\\" +
                        "ocelot\\config\\default");

        docGenerator.generateFullDoc();
        docGenerator.generateHTML();
        docGenerator.saveHTML("C:\\Users\\awi\\Documents\\GitHub\\" +
                "inspectit-ocelot-configuration-docs\\inspectit-ocelot-configuration-docs\\" +
                "inspectit-ocelot-config-docs\\src\\main\\resources\\");

        int i = 1;
    }
}
